server:
  port: 8080

spring:
  datasource:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:mysql://localhost:3306/db_course?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true